In [1]:
import numpy as np
numbers = np.array([1,2,3,4,5,6])
numbers

array([1, 2, 3, 4, 5, 6])

In [2]:
type(numbers)

numpy.ndarray

In [3]:
array_1d = np.array([1,2,3,4])

In [5]:
array_2d = np.array([[1,2,3,4],[1,2,3,4]])

In [6]:
array_3d = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [7]:
array_1d 

array([1, 2, 3, 4])

In [8]:
array_2d 

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [9]:
array_3d 

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [10]:
intigers = np.array([1,2,3,4])
intigers

array([1, 2, 3, 4])

In [12]:
float = np.array([0.0,0.1,0.2,0.3,0.4])
float

array([0. , 0.1, 0.2, 0.3, 0.4])

In [13]:
strings = np.array(['rahat','jim','chowa','jaky','tahosin'])
strings

array(['rahat', 'jim', 'chowa', 'jaky', 'tahosin'], dtype='<U7')

In [14]:
intigers.dtype

dtype('int64')

In [15]:
float.dtype

dtype('float64')

In [16]:
strings.dtype

dtype('<U7')

In [17]:
array_1d.ndim

1

In [18]:
array_2d.ndim

2

In [19]:
array_3d.ndim

3

In [21]:
array_2d.shape

(2, 4)

In [22]:
array_2d.reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [23]:
array_3d.shape

(1, 3, 4)

In [24]:
array_3d.size

12

In [25]:
array_2d.size

8

In [26]:
array_1d.size

4

In [29]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [30]:
x+10

array([10, 11, 12, 13])

In [31]:
x*2

array([0, 2, 4, 6])

In [32]:
x+x

array([0, 2, 4, 6])

In [33]:
x/10

array([0. , 0.1, 0.2, 0.3])

In [34]:
x**3

array([ 0,  1,  8, 27])

In [35]:
x**2

array([0, 1, 4, 9])

In [36]:
x>=10

array([False, False, False, False])

In [37]:
x>2

array([False, False, False,  True])

In [40]:
y = x**3
y>=9

array([False, False, False,  True])

In [41]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [43]:
grades.ndim

2

In [44]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [45]:
grades.max()

100

In [48]:
grades.min()

70

In [49]:
grades.sum()

1054

In [50]:
grades.std()

8.792357792739987

In [51]:
grades.mean()

87.83333333333333

In [52]:
grades.var()

77.30555555555556

In [53]:
grades.mean(axis = 0)

array([95.25, 85.25, 83.  ])

In [55]:
grades.max(axis =1)

array([ 96, 100,  94, 100])

In [56]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
array[1]

array([5, 6, 7, 8])

In [59]:
array[1][0]

5

In [63]:
array[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])